### ISSUE TITLE
Fazer o mapa do site do projeto

### ISSUE THREAD

**Issue by mateusnoites** [anjosoff/Noo#1]
Fazer o mapa do site do projeto e colocar no readme desse repositório, além de criar um arquivo txt em outra branch com as descrições de cada página do site.

**Comment by Jun-iper-o** [comment]
https://www.figma.com/file/hSYVbAJPKNv5wBTFWzasCF/Untitled?type=whiteboard&node-id=0%3A1&t=t65uVSK7TTOFu7DJ-1

**Comment by Jun-iper-o** [comment]
[páfinas.txt.docx](https://github.com/anjosoff/Noo/files/11556828/pafinas.txt.docx)
